'use strict';
const $ = id => document.getElementById(id);
const iconPaths = {
 chat:'<path d="M21 11.5a8.5 8.5 0 0 1-8.5 8.5H4l-2 2v-9.5A8.5 8.5 0 0 1 10.5 4H13a8 8 0 0 1 8 7.5Z"/><path d="M7 10h10M7 14h6"/>',
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 book:'<path d="M12 5v16M3 3h5a4 4 0 0 1 4 2 4 4 0 0 1 4-2h5v16h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3Z"/>',
 leaf:'<path d="M20 3C8 2 2 7 5 15s16 4 15-12Z"/><path d="M3 21 15 9M8 16v-5M8 16h5"/>',
 sprout:'<path d="M12 22V12M12 15C3 16 2 9 3 5c8-1 10 5 9 10ZM12 12c0-7 4-10 10-9 0 7-4 10-10 9Z"/>',
 sparkles:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4M18 4h4"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.5 1.5M17.5 17.5 19 19M5 19l1.5-1.5M17.5 6.5 19 5"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>'
};
function icons(root=document) { root.querySelectorAll('[data-icon]').forEach(el => { el.innerHTML = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[el.dataset.icon] || iconPaths.leaf}</svg>`; }); }
function el(tag, cls, text) { const node=document.createElement(tag); if(cls) node.className=cls; if(text!==undefined) node.textContent=text; return node; }
let toastTimer;
function toast(text) { $('toast').textContent=text; $('toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').hidden=true,5000); }
const STORAGE='weedbuddy.v1';
let state={theme:'dark',strains:[],chats:[]};
try { const saved=JSON.parse(localStorage.getItem(STORAGE)); if(saved && Array.isArray(saved.strains) && Array.isArray(saved.chats)) state={theme:saved.theme==='light'?'light':'dark',strains:saved.strains.filter(s=>s&&typeof s.name==='string'&&typeof s.id==='string'),chats:saved.chats.filter(c=>c&&typeof c.id==='string'&&Array.isArray(c.messages))}; }
catch { setTimeout(()=>toast('Saved data could not be loaded. This session still works, but export anything you want to keep.'),100); }
function persist(next) { try {localStorage.setItem(STORAGE,JSON.stringify(next)); state=next; return true;} catch {toast('Browser storage is unavailable or full. Your changes were not saved. Export your collection or use a smaller photo.');return false;} }
function uid() { return globalThis.crypto?.randomUUID?.() || Date.now().toString(36)+Math.random().toString(36).slice(2); }
let currentChat=null, draftPhoto='', photoBusy=false, photoVersion=0;
function theme() { document.documentElement.dataset.theme=state.theme; $('theme-label').textContent=`Switch to ${state.theme==='dark'?'light':'dark'} mode`; document.querySelector('meta[name="theme-color"]').content=state.theme==='dark'?'#111412':'#f6f7f2'; }
function closeMenu() { $('sidebar').classList.remove('open'); $('scrim').hidden=true; $('mobile-menu').setAttribute('aria-expanded','false'); }
function route() { const page=['chat','gallery','learn'].includes(location.hash.slice(1))?location.hash.slice(1):'chat'; for(const name of ['chat','gallery','learn']) { $(name+'-view').hidden=name!==page; $('nav-'+name).classList.toggle('active',name===page); if(name===page) $('nav-'+name).setAttribute('aria-current','page'); else $('nav-'+name).removeAttribute('aria-current'); } $('page-label').textContent={chat:'Your buddy',gallery:'Strain collection',learn:'The little guide'}[page]; $('page-label').append(el('span','version-tag','EARLY DAYS')); closeMenu(); if(page==='gallery') renderGallery(); }
function renderHistory() { const list=$('chat-history');list.replaceChildren(); $('history-empty').hidden=state.chats.length>0; state.chats.forEach(chat=> {const row=el('div','history-row'),open=el('button','',chat.title||'A new conversation'),remove=el('button','history-delete','×');open.title=chat.title||'Open conversation';open.onclick=()=>{currentChat=chat.id;location.hash='chat';renderMessages();closeMenu();};remove.setAttribute('aria-label','Delete conversation '+(chat.title||''));remove.onclick=()=>{if(!confirm('Delete this conversation from this browser?'))return;if(persist({...state,chats:state.chats.filter(c=>c.id!==chat.id)})){if(currentChat===chat.id)currentChat=null;renderHistory();renderMessages();}};row.append(open,remove);list.append(row); }); }
function renderMessages() { const chat=state.chats.find(c=>c.id===currentChat);$('welcome').hidden=!!chat;$('messages').hidden=!chat;$('messages').replaceChildren(); if(!chat)return;chat.messages.forEach(message=>{const node=el('article','message '+(message.role==='user'?'user':'assistant'));if(message.role==='user')node.textContent=String(message.content);else{const body=el('div','message-body');body.append(el('strong','', 'WeedBuddy'),el('p','',String(message.content)),el('small','','CURATED STARTER RESPONSE'));node.append(el('span','message-avatar','✳'),body);}$('messages').append(node);}); }
const guides=[
 {icon:'leaf',title:'A name is only the beginning.',text:'Indica, sativa, and hybrid are broad labels, not reliable promises about how you will feel. Your batch, cannabinoid content, personal tolerance, and setting matter more.',prompt:'Help me understand cannabis strains'},
 {icon:'sparkles',title:'A more comfortable session.',text:'Choose a familiar setting, skip mixing with alcohol, and make a plan that never involves driving. Keep products clearly labeled, locked away, and out of reach of children and pets.',prompt:'Share some tips for a more comfortable session'},
 {icon:'sprout',title:'Before you think about a grow.',text:'First check your local rules, age requirements, lease, and any licensing requirements. Think about child and pet access, electrical safety, moisture, and mold before setting up a space.',prompt:'What should I know before starting a legal grow?'},
 {icon:'book',title:'Keep a little strain journal.',text:'Save the batch label, date, aroma, and your own experience. Record THC and CBD from a tested product label, not a generic online average. Your notes are more useful than someone else’s hype.',prompt:'How do I keep a useful strain journal?'}
];
function answer(prompt) { const p=prompt.toLowerCase();if(/chest pain|can't breathe|cannot breathe|unconscious|seizure/.test(p))return 'If someone has chest pain, trouble breathing, a seizure, or is unresponsive, contact emergency services now. Do not leave them alone or let them drive. In the U.S., Poison Control is available at 1-800-222-1222. This starter chat cannot assess an emergency.';
 if(/anxious|panic|too high|uncomfortable/.test(p))return 'If you feel uncomfortable, stop using cannabis, move somewhere quiet and familiar, and stay with a trusted sober person. Avoid alcohol and other substances, and do not drive. Sip water normally and give yourself time.\n\nFor severe symptoms, chest pain, trouble breathing, or loss of consciousness, seek emergency help. If you are unsure, contact a poison center or healthcare professional.';
 if(/grow|soil|plant|light|harvest/.test(p))return 'A good starting point is making sure a home grow is legal where you live. Check the official local rules, any licensing requirements, and your lease before investing in equipment.\n\nFor the space itself, prioritize safe electrical installations, preventing moisture and mold, and keeping children and pets out. A licensed local horticulture professional can help you assess a legal setup.\n\nThis offline starter contains a pre-grow safety overview, not a personalized cultivation plan or live growing advisor.';
 if(/journal|save|collection|gallery|photo/.test(p))return 'Your collection is a good place to start. Open Strain collection, choose Add a strain, and give it a name and a photo. You can upload a photo, use a supported phone camera, or paste a direct image URL.\n\nSave the date, your experience, aromas, rating, and the THC/CBD values printed on your batch label. Add a source link if you have a lab report. Six familiar names have starter lineage notes, but they are not verified batch data.\n\nEverything stays in this browser. Use the menu at the bottom left to export a backup.';
 if(/strain|indica|sativa|hybrid|terpene|thc|cbd/.test(p))return 'Think of a strain name as a starting point, not a promise. “Indica,” “sativa,” and “hybrid” do not reliably predict effects on their own. Different batches with the same name can vary.\n\nThe useful details are the tested THC/CBD content, product type, batch information, and your own experience. Aromas can be interesting to record, but they do not guarantee a particular effect.\n\nTry keeping those details together in your Strain collection. Avoid assuming a strain will treat a health condition, and ask a clinician about medication interactions.';
 if(/session|tip|stoner|edible|smok|safe|storage/.test(p))return 'A few things worth keeping in mind:\n\n• Choose a familiar setting and trusted company.\n• Do not drive or operate machinery after using cannabis.\n• Avoid mixing cannabis with alcohol or other intoxicants.\n• Edibles can take much longer to take effect than expected. Avoid taking more because you do not feel it yet.\n• Store products in clearly labeled, child-resistant containers, away from children and pets.\n\nSmoking can harm your lungs. If you use medications, have a health condition, or are pregnant, talk with a healthcare professional about the risks.';
 return 'Hey, bud. This version of WeedBuddy has a small library of curated responses, rather than a connected AI model, so I can’t reliably answer that specific question yet.\n\nTry asking about strain labels, a comfortable session, keeping a strain journal, or what to consider before a legal grow. You can also build your personal strain collection right now.'; }
function submitMessage(text) { text=text.trim().slice(0,4000);if(!text)return; const existing=state.chats.find(c=>c.id===currentChat);const chat=existing?{...existing,messages:[...existing.messages]}:{id:uid(),title:text.slice(0,48),messages:[]};chat.messages.push({role:'user',content:text},{role:'assistant',content:answer(text)}); const next={...state,chats:[chat,...state.chats.filter(c=>c.id!==chat.id)]};if(!persist(next))return;currentChat=chat.id;$('message-input').value='';resizeComposer();location.hash='chat';renderMessages();renderHistory();closeMenu();requestAnimationFrame(()=>$('chat-form').scrollIntoView({block:'end',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})); }
function resizeComposer() {const input=$('message-input');input.style.height='auto';input.style.height=Math.min(input.scrollHeight,140)+'px';$('send-button').disabled=!input.value.trim();}
const profiles={
 'blue dream':{type:'Hybrid',lineage:'Commonly reported: Blueberry × Haze',flavors:'Often described as berry, sweet, herbal'},
 'og kush':{type:'Hybrid',lineage:'Disputed / not reliably established',flavors:'Often described as earthy, pine, citrus'},
 'sour diesel':{type:'Sativa',lineage:'Disputed / not reliably established',flavors:'Often described as diesel, citrus'},
 'granddaddy purple':{type:'Indica',lineage:'Commonly reported: Purple Urkle × Big Bud',flavors:'Often described as grape, berry'},
 'jack herer':{type:'Sativa',lineage:'Commonly reported: Haze, Northern Lights #5, Shiva Skunk',flavors:'Often described as pine, spice'},
 'northern lights':{type:'Indica',lineage:'Commonly described as Afghani / Thai ancestry; varies by breeder',flavors:'Often described as earthy, sweet, pine'}
};
function safeURL(value,allowData=false) { if(!value)return '';if(allowData&&/^data:image\/(jpeg|png|webp);base64,[a-z\d+/=]+$/i.test(value))return value;try{const url=new URL(value);return url.protocol==='https:'||url.protocol==='http:'?url.href:'';}catch{return '';} }
function photoNode(src,name) { const image=el('img');image.alt=name;image.loading='lazy';image.referrerPolicy='no-referrer';image.src=safeURL(src,true);image.onerror=()=>image.replaceWith(el('span','placeholder-leaf','✳'));return image; }
function renderGallery() { $('collection-count').textContent=state.strains.length;const grid=$('strain-grid');grid.replaceChildren();$('gallery-empty').hidden=state.strains.length>0;const q=$('strain-search').value.trim().toLowerCase(),type=$('strain-filter').value;const filtered=state.strains.filter(s=>(type==='all'||s.type===type)&&[s.name,s.notes,s.flavors,s.effects].join(' ').toLowerCase().includes(q));if(state.strains.length&&!filtered.length){grid.append(el('div','no-results','No strains found. Try another name or choose All types.'));return;}filtered.forEach(s=>{const card=el('button','strain-card');card.setAttribute('aria-label','View or edit '+s.name);card.onclick=()=>openStrain(s);const photo=el('div','strain-image');photo.append(safeURL(s.photo,true)?photoNode(s.photo,s.name):el('span','placeholder-leaf','✳'),el('span','strain-type',s.type||'Unknown'));const body=el('div','strain-card-body'),meta=el('div','strain-meta');const rating=Math.min(5,Math.max(0,Number(s.rating)||0));meta.append(el('span','',s.thc!==''&&s.thc!=null?`THC ${s.thc}%`:'THC not recorded'),el('span','stars',rating?'★'.repeat(rating):'Not rated'));body.append(el('h2','',s.name),meta,el('p','',s.effects||s.flavors||'Your next little discovery.'));card.append(photo,body);grid.append(card);}); }
const fields=['name','type','thc','cbd','date','lineage','flavors','effects','rating','source','notes'];
function renderPhoto() {const preview=$('photo-preview');preview.replaceChildren();if(draftPhoto)preview.append(photoNode(draftPhoto,'Strain photo preview'));else preview.append(el('span','','✳'),el('small','','A face for the name'));}
function openStrain(strain=null) { photoVersion++;photoBusy=false;$('strain-form').reset();$('strain-id').value=strain?.id||'';fields.forEach(key=>{if(strain&&strain[key]!=null)$('strain-'+key).value=strain[key];});draftPhoto=strain?.photo||'';$('photo-url').value=draftPhoto.startsWith('http')?draftPhoto:'';$('form-error').textContent='';$('lookup-status').textContent='Six starter profiles available. Not a live database. Verify against your batch label.';$('dialog-title').textContent=strain?'A strain worth remembering.':'Meet your next memory.';$('delete-strain').hidden=!strain;renderPhoto();$('strain-dialog').showModal(); }
async function uploadPhoto(event) {const file=event.target.files[0];if(!file)return;const version=++photoVersion;if(!/^image\/(jpeg|png|webp|gif|avif)$/.test(file.type)){$('form-error').textContent='Please choose a JPG, PNG, WebP, GIF, or AVIF image. Convert HEIC photos to JPG first.';event.target.value='';return;}if(file.size>15*1024*1024){$('form-error').textContent='Choose a photo smaller than 15 MB.';return;}photoBusy=true;$('form-error').textContent='Preparing your photo…';const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const scale=Math.min(1,1000/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);if(version!==photoVersion)return;draftPhoto=canvas.toDataURL('image/jpeg',.78);$('photo-url').value='';renderPhoto();$('form-error').textContent='';}catch{if(version===photoVersion)$('form-error').textContent='This photo could not be opened. Try another image.';}finally{URL.revokeObjectURL(url);if(version===photoVersion)photoBusy=false;event.target.value='';} }
$('strain-form').onsubmit=event=>{event.preventDefault();if(photoBusy){$('form-error').textContent='Please wait for your photo to finish preparing.';return;}const strain={id:$('strain-id').value||uid(),photo:draftPhoto};fields.forEach(key=>strain[key]=$('strain-'+key).value.trim());if(!strain.name){$('form-error').textContent='Give this strain a name first.';$('strain-name').focus();return;}const url=$('photo-url').value.trim();if(url&&!safeURL(url)){$('form-error').textContent='Use an http or https image URL.';return;}if(strain.source&&!safeURL(strain.source)){$('form-error').textContent='Use an http or https source URL.';return;}if(url)strain.photo=safeURL(url);if(!persist({...state,strains:[strain,...state.strains.filter(s=>s.id!==strain.id)]})){$('form-error').textContent='Could not save. Browser storage may be full or disabled. Try a smaller photo.';return;}$('strain-dialog').close();renderGallery();toast('A little memory, saved.');};
$('lookup-strain').onclick=()=>{const profile=profiles[$('strain-name').value.trim().toLowerCase()];if(!profile){$('lookup-status').textContent='No starter profile for that name. Add details from your product label or a trusted reference.';return;}for(const key of ['type','lineage','flavors'])if(!$('strain-'+key).value||$('strain-'+key).value==='Unknown')$('strain-'+key).value=profile[key];$('lookup-status').textContent='Added general, unverified starter notes to empty fields. Potency and personal effects are intentionally left for your batch and experience.';};
$('delete-strain').onclick=()=>{if(!confirm('Delete this strain and its photo from your collection?'))return;if(persist({...state,strains:state.strains.filter(s=>s.id!==$('strain-id').value)})){$('strain-dialog').close();renderGallery();toast('Strain removed.');}};
['close-dialog','cancel-dialog'].forEach(id=>$(id).onclick=()=>$('strain-dialog').close());
$('strain-dialog').addEventListener('close',()=>{photoVersion++;photoBusy=false;});
['photo-upload','photo-camera'].forEach(id=>$(id).onchange=uploadPhoto);
$('remove-photo').onclick=()=>{photoVersion++;photoBusy=false;draftPhoto='';$('photo-url').value='';$('form-error').textContent='';renderPhoto();};
$('photo-url').onchange=()=>{photoVersion++;photoBusy=false;const url=$('photo-url').value.trim();if(url&&!safeURL(url)){$('form-error').textContent='Use an http or https image URL.';return;}draftPhoto=safeURL(url);$('form-error').textContent='';renderPhoto();};
['add-strain','first-strain'].forEach(id=>$(id).onclick=()=>openStrain());
$('strain-search').oninput=renderGallery;$('strain-filter').onchange=renderGallery;
$('chat-form').onsubmit=e=>{e.preventDefault();submitMessage($('message-input').value);};$('message-input').oninput=resizeComposer;
$('message-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();submitMessage(e.target.value);}};
document.querySelectorAll('[data-action="new-chat"]').forEach(button=>button.onclick=()=>{currentChat=null;location.hash='chat';renderMessages();closeMenu();$('message-input').focus();});
document.querySelectorAll('[data-prompt]').forEach(button=>button.onclick=()=>submitMessage(button.dataset.prompt));
$('profile-button').onclick=()=>{const open=$('settings-menu').hidden;$('settings-menu').hidden=!open;$('profile-button').setAttribute('aria-expanded',String(open));};
$('theme-toggle').onclick=()=>{const next={...state,theme:state.theme==='dark'?'light':'dark'};if(persist(next))theme();};
$('export-button').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),strains:state.strains},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='weedbuddy-collection-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Collection exported. Keep this file somewhere safe.');};
 $('mobile-menu').onclick=()=>{const open=!$('sidebar').classList.contains('open');$('sidebar').classList.toggle('open',open);$('scrim').hidden=!open;$('mobile-menu').setAttribute('aria-expanded',String(open));};$('scrim').onclick=closeMenu;document.querySelectorAll('.nav-item').forEach(item=>item.onclick=()=>{location.hash=item.id.slice(4);route();});
document.addEventListener('click',e=>{if(!e.target.closest('.settings-wrap')){$('settings-menu').hidden=true;$('profile-button').setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();$('settings-menu').hidden=true;$('profile-button').setAttribute('aria-expanded','false');}});
window.addEventListener('hashchange',route);
window.addEventListener('storage',event=>{if(event.key===STORAGE)toast('Your data changed in another tab. Reload before making more edits.');});
guides.forEach(guide=>{const card=el('article','guide-card'),icon=el('span');icon.dataset.icon=guide.icon;const button=el('button','','Talk about this ↗');button.onclick=()=>submitMessage(guide.prompt);card.append(icon,el('h2','',guide.title),el('p','',guide.text),button);$('guide-grid').append(card);});
icons();theme();renderHistory();renderGallery();route();
